name: CI Build, Test and Push

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      cockroachdb:
        image: cockroachdb/cockroach:v23.1.4
        ports:
          - 26257:26257
          - 8080:8080
        options: >-
          --health-cmd="cockroach sql --insecure -e 'SELECT 1'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration Release

      - name: Wait for CockroachDB to be ready
        run: |
          for i in {1..10}; do
            cockroach sql --insecure --host=localhost:26257 -e "SELECT 1" && break
            echo "Waiting for CockroachDB to be ready..."
            sleep 5
          done

      - name: Run tests
        env:
          ConnectionStrings__CockroachDb: "Host=localhost;Port=26257;Database=appdb;Username=root;Password=;SSL Mode=Disable"
        run: dotnet test --no-build --verbosity normal

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t htdung/crud-newsql:latest .

      - name: Push Docker image
        run: docker push htdung/crud-newsql:latest